version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - &restore_python_cache
        restore_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}
      - &install_dependencies
        run:
          name: install python dependencies
          command: |
            virtualenv env
            source env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - &save_python_cache
        save_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: run tests
          command: |
            source env/bin/activate
            ./scripts/validate-workflows.sh
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - *restore_python_cache
      - *install_dependencies
      - *save_python_cache
      - run:
          name: "Pack and upload workflow to GitHub release"
          command: |
            python scripts/release.py ${GITHUB_TOKEN} ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*v[0-9]+/
            branches:
              ignore: /.*/
